service: customer-document-uploads

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: eu-west-2
  apiGateway:
    binaryMediaTypes:
      - 'multipart/form-data'
      - '*/*'
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - s3:PutObject
        - s3:GetObject
        - s3:DeleteObject
      Resource: '*'
  environment:
    DROPBOXES_TABLE: '${self:service}-${self:provider.stage}-dropboxes'
    UPLOADS_BUCKET: '${self:service}-${self:provider.stage}-uploads'
    SENTRY_DSN: ${ssm:/customer-document-uploads/SENTRY_DSN}
    jwtsecret: ${ssm:/common/hackney-jwt-secret}
    stage: ${self:provider.stage}

custom:
  dynamodb:
    stages:
      - ${self:provider.stage}
    start:
      port: 8000
      inMemory: true
      migrate: true
  s3:
    port: 8100
    directory: ./.s3local
    host: localhost
    address: localhost
    allowMismatchedSignatures: true

plugins:
  - serverless-offline
  - serverless-offline-ssm
  - serverless-dynamodb-local
  - serverless-s3-local

package:
  individually: true
  exclude:
    - ./**

functions:
  root:
    handler: root.handler
    package:
      include:
        - root.js
    events:
      - http:
          path: /
          method: GET
  saveDropbox:
    handler: lambda.saveDropboxHandler
    package:
      include:
        - lambda.js
        - lib/**
        - static/**
        - templates/**
        - node_modules/**
    events:
      - http:
          path: '/dropboxes/{dropboxId}'
          method: POST
  app:
    handler: lambda.handler
    package:
      include:
        - lambda.js
        - lib/**
        - static/**
        - templates/**
        - node_modules/**
    events:
      - http:
          path: '{proxy+}'
          method: ANY

resources:
  Resources:
    UploadsBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:provider.environment.UPLOADS_BUCKET}
        PublicAccessBlockConfiguration:
          BlockPublicAcls: true
          BlockPublicPolicy: true
          IgnorePublicAcls: true
          RestrictPublicBuckets: true
        BucketEncryption:
          ServerSideEncryptionConfiguration:
            - ServerSideEncryptionByDefault:
                SSEAlgorithm: AES256
    UploadsDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: dropboxId
            AttributeType: S
        KeySchema:
          - AttributeName: dropboxId
            KeyType: HASH
        BillingMode: PROVISIONED
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
        TableName: ${self:provider.environment.DROPBOXES_TABLE}
