version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12.13

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-

      - run:
          name: Install Serverless CLI, eslint, and dependencies
          command: |
            sudo npm i -g serverless
            sudo npm i -g eslint
            npm install

      - run:
          name: Run linting
          command: npm run lint

      - run:
          name: Set AWS credentials
          command: |
            serverless config credentials --provider aws --key ${AWS_ACCESS_KEY_ID} --secret ${AWS_SECRET_ACCESS_KEY} --profile docuploads

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}

      - run:
          name: Deploy application
          command: sls deploy -s production
