version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12.13

    working_directory: ~/repo

    steps:
      - checkout

      # - restore_cache:
      #     keys:
      #       - v1-dependencies-{{ checksum "package-lock.json" }}

      - run:
          name: Install dependencies
          command: |
            sudo apt-get update && sudo apt-get install default-jre
            npm install
            ./node_modules/serverless/bin/serverless dynamodb install
            sudo apt-get install libxss1

      - run:
          name: Run linting
          command: npm run lint

      - run:
          name: Run tests
          command: |
            echo "/customer-document-uploads/SENTRY_DSN=my_sentry_dsn\n/common/hackney-jwt-secret=my_secret" >> .env
            npm run ci

      - run:
          name: Set AWS credentials
          command: |
            ./node_modules/serverless/bin/serverless config credentials --provider aws --key ${AWS_ACCESS_KEY_ID} --secret ${AWS_SECRET_ACCESS_KEY} --profile docuploads

      # - save_cache:
      #     paths:
      #       - node_modules
      #     key: v1-dependencies-{{ checksum "package-lock.json" }}

      - run:
          name: Deploy application
          command: ./node_modules/serverless/bin/serverless deploy -s production
