version: 2.1

executors:
  node:
    docker:
      - image: circleci/node:12.13

    working_directory: ~/repo

jobs:
  build:
    executor: node

    steps:
      - checkout

      # - restore_cache:
      #     keys:
      #       - v1-dependencies-{{ checksum "package-lock.json" }}

      - run:
          name: Install dependencies
          command: |
            sudo apt-get update && sudo apt-get install default-jre
            npm install
            ./node_modules/serverless/bin/serverless dynamodb install
            sudo apt-get install libxss1

      - run:
          name: Run linting
          command: npm run lint

      - run:
          name: Run tests
          environment:
            CYPRESS_JWT_SECRET: my_secret
          command: |
            echo -e "/customer-document-uploads/SENTRY_DSN=my_sentry_dsn\n/common/hackney-jwt-secret=my_secret" >> .env
            npm run ci

      - persist_to_workspace:
          root: ~/repo
          paths: .
  
  deploy:
    executor: node

    steps:
      - attach_workspace:
          at: ~/repo

      - run:
          name: Set AWS credentials
          command: |
            ./node_modules/serverless/bin/serverless config credentials --provider aws --key ${AWS_ACCESS_KEY_ID} --secret ${AWS_SECRET_ACCESS_KEY} --profile docuploads

      - run:
          name: Deploy application
          command: ./node_modules/serverless/bin/serverless deploy -s production

workflows:
  version: 2
  build-and-deploy-when-master:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
